### ISSUE TITLE
Download Link is dead

### ISSUE THREAD

**Issue by troubas** [ganwell/vim-hunspell-dicts#1]
Hi and thank you for this project.
I've been using it for quite a while now and it's great!

Currently (sadly) the download link [http://1042.ch/spell/](url) is dead. 
Also I can't build the project but I'll create a seperate ticket for that ;)

**Comment by ganwell** [comment]
Hi, I fixed the download link. Sorry. I moved to domain to another server.

**Comment by troubas** [comment]
thanks!
