### ISSUE TITLE
Make fails 'no rule to make target'

### ISSUE THREAD

**Issue by troubas** [ganwell/vim-hunspell-dicts#2]
Can't figure out why this is happening. For me the rule looks perfectly fine. However make seems to differ: `make: *** No rule to make target 'outfiles/hun-de-CH.utf-8.spl', needed by 'all'.  Stop.`

Figured maybe you know some magic trick?

**Comment by ganwell** [comment]
@troubas The trick is to use bsd make instread of gnu make, but since I am on linux now, I use a simple shell script.
